=== danyaleffendi/Support-Ticket-System/xml/tickets.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="tickets">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="ticket">
          <xs:complexType>            
            <xs:sequence>
              <xs:element name="issueDate">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:dateTime">
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="status" type="xs:string" />
              <xs:element name="subject" type="xs:string" />
              <xs:element name="orderId" type="xs:string" />
              <xs:element name="messages">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="message">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="userId" type="xs:positiveInteger" use="required" />
                            <xs:attribute name="datetime" type="xs:dateTime" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
              <xs:attribute name="id" type="xs:positiveInteger" use="required" />
              <xs:attribute name="userid" type="xs:positiveInteger" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

    <xs:simpleType name="status">
    <xs:restriction base="xs:string">
      <xs:enumeration value="resolved"></xs:enumeration>
      <xs:enumeration value="in-process"></xs:enumeration>
      <xs:enumeration value="new"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== danyaleffendi/Support-Ticket-System/xml/tickets.xml
<?xml version="1.0" encoding="utf-8"?>
<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tickets.xsd">
    <ticket id="101" userid="13">
        <issueDate>2021-02-02T08:03:55</issueDate>
        <status>In-process</status>
        <subject>Order Question</subject>
        <orderId>11337</orderId>
        <messages>
            <message userId="13" datetime="2021-02-02T08:03:57">
                When would I receive my order?
            </message>
            <message userId="11" datetime="2021-02-02T10:38:50">
                Thank you for contacting us. Your order will be delivered on Feb 4, 2021 at around 5 pm.
            </message>
            <message userId="13" datetime="2021-04-05T02:10:40+02:00">okay thanks</message>
            <message userId="11" datetime="2021-04-05T03:01:49+02:00">testing 123</message>
            <message userId="12" datetime="2021-04-05T04:57:37+02:00">c test</message><message userId="13" datetime="2021-04-05T05:04:09+02:00">c1 test</message><message userId="13" datetime="2021-04-05T05:37:26+02:00">c1 test</message>
            <message userId="13" datetime="2021-04-05T07:14:15+02:00">testing new ticket</message><message userId="13" datetime="2021-04-05T18:24:10+02:00">testing msg time</message>
        </messages>
    </ticket>
    <ticket id="102" userid="12">
        <issueDate>2021-02-06T21:01:55</issueDate>
        <status>Resolved</status>
        <subject>Shipping</subject>
        <orderId>12345</orderId>
        <messages>
            <message userId="13" datetime="2021-02-06T21:01:57">
                When will my order be shipped?
            </message>
            <message userId="12" datetime="2021-02-17T21:03:47">
                Your order has been shipped today.
            </message>
            <message userId="13" datetime="2021-04-05T02:10:40+02:00">okay thanks</message>
            <message userId="11" datetime="2021-04-05T03:01:49+02:00">testing 123</message>
        </messages>
    </ticket>
    <ticket id="103" userid="11">
        <issueDate>2021-02-04T17:57:35</issueDate>
        <status>In-Process</status>
        <subject>Product Availability</subject>
        <orderId>FF123</orderId>
        <messages>
            <message userId="13" datetime="2021-02-04T17:57:37">
                Is this top still available?
            </message>
            <message userId="11" datetime="2021-02-04T18:01:14">
                Thank you for contacting us. Could you please specify which product with a product link or ID?
            </message>
            <message userId="13" datetime="2021-04-05T02:10:40+02:00">okay thanks</message>
            <message userId="12" datetime="2021-04-05T03:01:49+02:00">testing 123</message>
            <message userId="11" datetime="2021-04-05T04:54:20+02:00">bk test</message>
        </messages>
    </ticket>
    <ticket id="104" userid="13">
        <issueDate>2021-04-05T08:29:15+02:00</issueDate><status>Resolved</status><subject>testing auto increment</subject><orderId>DD124</orderId>
        <messages>
            <message userId="13" datetime="2021-04-05T08:29:15+02:00">testing ai</message><message userId="12" datetime="2021-04-05T08:32:33+02:00">check 123</message><message userId="11" datetime="2021-04-05T08:32:52+02:00">ok</message>
        </messages>
    </ticket>
    <ticket id="105" userid="14">
        <issueDate>2021-04-05T20:57:23+02:00</issueDate><status>Resolved</status><subject>I want a refund</subject><orderId>BC546</orderId>
        <messages>
            <message userId="14" datetime="2021-04-05T20:57:23+02:00">I have return your product. please refund me asap.</message>
            <message userId="12" datetime="2021-04-05T21:00:34+02:00">your refund has been processed. The bank will take 3-5 days. thanks</message>
        </messages>
    </ticket>
    <ticket id="106" userid="12">
        <issueDate>2021-04-05T20:59:57+02:00</issueDate><status>New</status><subject>this customer having issue on website</subject><orderId>NA</orderId>
        <messages><message userId="12" datetime="2021-04-05T20:59:57+02:00">username abc123&#13; not able to order online</message> <message userId="11" datetime="2021-04-21T05:55:17+02:00">testing</message></messages>
    </ticket>
</tickets>
